### ISSUE TITLE
中国以外时的地址转换

### ISSUE THREAD

**Issue by apache2046** [JackZhouCn/JZLocationConverter#3]
// 此接口当输入坐标为中国大陆以外时，仍旧返回WGS-84坐标
// + (CLLocationCoordinate2D)wgs84ToGcj02:(CLLocationCoordinate2D)location;

底层实现中，这种简单的矩形范围判断，会把某些国家的区域误判为中国：
- (BOOL)outOfChina:(double)lat bdLon:(double)lon
  {
  if (lon < RANGE_LON_MIN || lon > RANGE_LON_MAX)
      return true;
  if (lat < RANGE_LAT_MIN || lat > RANGE_LAT_MAX)
      return true;
  return false;
  }

**Comment by LhiKien** [comment]
台湾地区使用的苹果手机上，使用的地图不存在偏差吧？
如何把台湾排除在外？

**Comment by JackZhouCn** [comment]
正如@apache2046 所说，部分地区和国家确实会误判，具体如何排除还在思考，事实上获取边境线坐标是个头疼的事，有没有好的想法？@LhiKien

**Comment by JackZhouCn** [comment]
@apache2046 这个问题在[新的repository](https://github.com/JackZhouCn/JZLocationConverter-Swift)解决了
@LhiKien [新的repository](https://github.com/JackZhouCn/JZLocationConverter-Swift)中台湾地区已经排除在外了
